variables:
  GIT_SUBMODULE_STRATEGY: recursive
  a11y_urls: 'https://www.skao.int/'
  JS_NODE_VERSION: 21

stages:
  - lint
  - build
  - test
  - scan
  - pages
  - deploy
  - accessibility
  - publish

k8s-test:
  script:
    - echo "There are no e2e tests targeting deployment here yet!"

pages:
  stage: pages
  tags:
    - k8srunner
  script:
    - mv public/* .
    - cp -r build/* public
    - cp -r .public/* public
  artifacts:
    paths:
      - public
    expire_in: 30 days

# -------------------- E2E TESTS --------------------
#test_and_coverage:
#  image: cypress/browsers:node18.12.0-chrome106-ff106
#  stage: test
#  tags:
#    - k8srunner
#  before_script:
#    - mkdir -p build/reports
#    - mkdir -p build/.nyc_output
#    - yarn install --frozen-lockfile
#  script:
#    - yarn start &
#    - yarn test:e2e:headless
#    - yarn test:coverage:report:ci
#    - cp build/reports/cobertura-coverage.xml build/reports/code-coverage.xml
#  coverage: /All\sfiles.*?\s+(\d+.\d+)/
#  artifacts:
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: build/reports/cobertura-coverage.xml
#    paths:
#      - build/
#
#test-counts:
#  image: cypress/browsers:node18.12.0-chrome106-ff106
#  stage: test
#  tags:
#    - k8srunner
#  cache:
#    paths:
#      - node_modules/
#    policy: pull
#  before_script:
#    - mkdir -p build/tests
#    - yarn install --immutable
#  script:
#    - yarn test:cypress:component:ci
#    - yarn merge-reports
#  artifacts:
#    paths:
#      - build/
# -------------------- E2E TESTS --------------------

include:
  - template: 'Verify/Accessibility.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/js.gitlab-ci.yml'
    ref: st-1948-react-skeleton-compat
    # OCI Images
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'
    # Helm Chart
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'
    # K8s check
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'
    # Tag Based GitLab Release Management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
  # .post step finalizers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
