image:
  imagePullPolicy: IfNotPresent
  container: registry.gitlab.com/ska-telescope/templates/ska-react-webapp-skeleton/ska-react-webapp-skeleton
  version: 0.0.0

ingress:
  prependByNamespace: true
